# fly.toml file generated for summer-dream-5405 on 2022-02-06T13:00:31-05:00

app = "summer-dream-5405"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DOMAIN = "summer-dream-5405.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = "start_with_migrations.sh"
  entrypoint = "sh"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
